pool:
  vmImage: ubuntu-18.04

trigger:
  - master

stages:
  - stage: Prepare
    jobs:
      - job: InstallAwsCdk
        steps:
          - bash: sudo npm install -g aws-cdk --allow-root
      
      - job: Deploy
        workingDirectory: infra
        steps:
          - bash: 
            - cdk diff
