pool:
  vmImage: ubuntu-18.04

trigger:
  - master

stages:
  - stage: Prepare
    jobs:
      - job: InstallAwsCdk
        variables:
          AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID_ENCRYPTED)
          AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY_ENCRYPTED)
        steps:
          - bash: |
              echo "AWS_ACCESS_KEY_ID is $AWS_ACCESS_KEY_ID $(AWS_ACCESS_KEY_ID_ENCRYPTED)"
              sudo npm install -g aws-cdk --allow-root
              cd infra
              npm install
              cdk diff
