pool:
  vmImage: ubuntu-18.04

trigger:
  - master

stages:
  - stage: Prepare
    jobs:
      - job: InstallAwsCli
        variables:
          AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
          AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
        steps:
            - bash: |
                curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
                unzip awscliv2.zip
                sudo ./aws/install
                aws s3 ls
      - job: InstallAwsCdk
        steps:
          - bash: |
              sudo npm install -g aws-cdk --allow-root
              cd infra 
              npm install
              cdk diff
