pool:
  vmImage: ubuntu-18.04

trigger:
  - master

stages:
  - stage: Prepare
    jobs:
      - job: BuildAndDeploy
        steps:
          - bash: |
              # Setup Environment
              export AWS_ACCESS_KEY_ID="$(AWS_ACCESS_KEY_ID_ENCRYPTED)"
              export AWS_SECRET_ACCESS_KEY="$(AWS_SECRET_ACCESS_KEY_ENCRYPTED)"
              export GIT_COMMIT="$(Build.SourceVersion)"

              REGISTRY="$(CDK_DEPLOY_ACCOUNT).dkr.ecr.ap-southeast-2.amazonaws.com"
              IMAGE_REPOSITORY="$REGISTRY/container-meetup-application"

              # Install AWS CLI
              curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
              unzip awscliv2.zip
              sudo ./aws/install

              # Install CDK
              sudo npm install -g aws-cdk --allow-root

              # Install CDK app for deploying environment and application infrastructure
              cd infra
              npm install

              # Deploy environment infrastructure changes
              # cdk deploy --require-approval never "container-meetup-environment"

              # Build and publish container
              cd ..
              docker build -t aspnetapp .
              docker tag aspnetapp "$IMAGE_REPOSITORY:$GIT_COMMIT" 
              aws ecr get-login-password | docker login -u AWS --password-stdin "https://$REGISTRY"
              docker push "$IMAGE_REPOSITORY:$GIT_COMMIT" 

              # Deploy the application
              cdk deploy --require-approval never "container-meetup-application"
