pool:
  vmImage: ubuntu-18.04

trigger:
  - master

stages:
  - stage: Prepare
    jobs:
      - job: InstallAwsCdk
        steps:
          - bash: |
              export AWS_ACCESS_KEY_ID="$(AWS_ACCESS_KEY_ID_ENCRYPTED)"
              export AWS_SECRET_ACCESS_KEY="$(AWS_SECRET_ACCESS_KEY_ENCRYPTED)"
              sudo npm install -g aws-cdk --allow-root
              cd infra
              npm install
